# training hparams
num_train_steps: 2000000
update_interval: 2000
num_epochs: 100
batch_size: 1024
gamma: 0.99
eps_clip: 0.2
action_std_init: 0.5
action_std_decay_rate: 0.05
min_action_std: 0.1
entropy_coef: 0.01
value_loss_coef: 0.5
max_grad_norm: 0.5
mode: "test"

# network hparams
agent: "ppo_icm"
hidden_dim: 64
activation: "tanh"
lr_actor: 3.0e-4
lr_critic: 1.0e-3

# icm_specific_params, work only when agent="ppo_icm"
lr_icm: 1.0e-3
icm_beta: 0.2
icm_eta: 0.01
intrinsic_coeff: 1

# env hparams
env_name: "BabyAI-FindObjS7-v0"
continuous_action_space: false
max_eps_steps: 400
random_seed: 42

# logging hparams
wandb_project: "ppo-experiments-minigrid-lava"
wandb_entity: "saqib1707"
exp_name: ""
# run_id: 1
# log_interval: ${max_eps_steps * 5}
# save_interval: ${max_eps_steps * 10}
log_interval: 10000
save_interval: 100000
log_dir: "./logs/"
ckpt_dir: ".logs/BabyAI-FindObjS7-v0/runs/run_20250823T131905/checkpoints/"

# evaluation hparams
num_eval_eps: 1
eval_ckpt_name: "BabyAI-FindObjS7-v0_policy_step_900000.pt"
render_mode: null